trigger:
  branches:
    include:
      - main
      - feature/*

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'macOS-15'

variables:
  derivedDataPath: '$(Build.SourcesDirectory)/DerivedData'
  artifactDir: '$(Build.SourcesDirectory)/azure-artifacts'

steps:
  - checkout: self
    clean: true
    fetchDepth: 1
